/* Created by Nikilesh Ramesh on 02/11/2024 at 13:47

Motivation: to create dummy user defined functions for testing the 
gradient computations, this should be ideally generated by MATLAB 
interface
*/

#include "UserDefinedFunctions.h"

const Cost E_unscaled (const States x0, const States xf, const Inputs u0, const Inputs uf,
    const Time t0, const Time tf
){
    const Cost E = xf[0]*uf[0]*tf; //dummy function xf(1)*uf(1)
    return E;
}