/*Created by Nikilesh Ramesh on 02/11/2024 at 13:30

Motivation: to create dummy user defined functions for testing the 
gradient computations, this should be ideally generated by MATLAB 
interface
*/

#ifndef __USER_DEFINED_FUNCTIONS__
#define __USER_DEFINED_FUNCTIONS__

#include "typeDefinitions.h"

const Cost E_unscaled (const States x0, const States xf, const Inputs u0, const Inputs uf,
    const Time t0, const Time tf
);

const Cost L_unscaled (const StateVectors X, const InputVectors U, const TimeVector T);

#endif